# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution ti
name: Java CI with Maven

on:
  workflow_dispatch:
    inputs:
      version:
      description: Dev build version 
      default: v1.0
      required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checking out git repo
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        cache: 'maven'
  
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: list current directory
      run: ls -a
      
    - name: Show target folder contents
      run: |
         cd target
         ls -a
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: argocdtest
        IMAGE_TAG: ${{ github.event.inputs.version }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

   
    
